[info]
name = "airport_terminal_fast_track"
description = "airport_terminal_fast_track for Multimodx project. Implements a faster kerb2gate time if a multimodal pax is delayed"
incompatibilities = []
requirements = []
get_metric = 'None'

[agent_modif]
    [agent_modif.AirportTerminal]
        on_init = "on_init_agent"
        new_parameters = [
            'fast_track_speed_up'
        ]

        [agent_modif.AirportTerminal.MoveGate2KerbTime]
        on_init = "on_init"
        wait_for_move_kerb2gate_times_request = "wait_for_move_kerb2gate_times_request_NEW"
        new_methods = [
        ]

receive = "receive_new_messages"


