name: Docker Image CI

on:
  push:
    branches: [ "test_docker_deployment" ]
#  pull_request:
#    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image for CLI
      run: |
            docker build -t mercury_cli . -f DockerfileCLI --tag mercury_cli:$(date +%s)
            docker tag mercury_cli:$(date +%s) ghcr.io/UoW-ATM/Mercury/mercury_cli:$(date +%s)
            docker push ghcr.io/UoW-ATM/Mercury/mercury_cli:$(date +%s)
    - name: Build the Docker image for Notebook
      run: | 
            docker build -t mercury_nb . -f DockerfileNotebook --tag mercury_nb:$(date +%s)
            docker tag mercury_nb:$(date +%s) ghcr.io/UoW-ATM/Mercury/mercury_nb:$(date +%s)
            docker push ghcr.io/UoW-ATM/Mercury/mercury_nb:$(date +%s)
